"use client";
import {useState,useEffect,useCallback,FormEvent} from 'react';
import {Users,CalendarDays,ShieldCheck,Plus,Download,Search,Settings2,History,Edit3,KeyRound,RefreshCw,LockKeyhole} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {toast} from 'sonner';
import {api,dateLabel,type AdminData,type User,type Settings,type Booking} from '@/lib/types';
function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(s:string)=>void;options:{value:string;label:string}[]}){return <label className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{options.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select></label>;}
function Input({label,...props}:{label:string}&React.InputHTMLAttributes<HTMLInputElement>){return <label className="field"><span>{label}</span><input required {...props}/></label>;}
export function AdminPanel({user,settings,revision,onChanged}:{user:User;settings:Settings;revision:number;onChanged:()=>Promise<void>}){
 const [data,setData]=useState<AdminData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[formError,setFormError]=useState('');
 const [search,setSearch]=useState(''),[statusFilter,setStatusFilter]=useState('all'),[modal,setModal]=useState<'reserve'|'block'|'user'|'password'|null>(null),[editing,setEditing]=useState<User|null>(null),[cancel,setCancel]=useState<Booking|null>(null);
 const [target,setTarget]=useState(''),[slot,setSlot]=useState('12'),[role,setRole]=useState('resident'),[status,setStatus]=useState('active');
 const [rules,setRules]=useState(settings.rules.replace(/\\n/g,'\n')),[advance,setAdvance]=useState(String(settings.advance_days)),[hours,setHours]=useState(String(settings.cancellation_hours));
 const load=useCallback(async()=>{setLoading(true);try{setData(await api<AdminData>('/api/admin'));setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load,revision]);
 const refresh=async()=>{await Promise.all([load(),onChanged()]);};
 function open(kind:typeof modal,u?:User){setFormError('');setModal(kind);setEditing(u??null);setRole(u?.role??'resident');setStatus(u?.status??'active');setTarget(data?.users.find(u=>u.role==='resident'&&u.status==='active')?.id??user.id);}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const b=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);setFormError('');try{if(modal==='reserve'||modal==='block'){await api('/api/bookings',{...b,action:modal,date:b.date,slot:Number(slot),userId:target,acceptRules:true});}else{await api('/api/admin',{...b,action:modal==='user'?'user':'resetPassword',id:editing?.id,role,status});}setModal(null);await refresh();toast.success('Cambios guardados.');}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}
 async function cancelTurn(){if(!cancel)return;setBusy(true);try{await api('/api/bookings',{action:'cancel',id:cancel.id});setCancel(null);await refresh();toast.success('Turno liberado.');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 async function saveSettings(e:FormEvent){e.preventDefault();setBusy(true);try{await api('/api/admin',{action:'settings',rules,advanceDays:Number(advance),cancellationHours:Number(hours)});await refresh();toast.success('Reglamento y plazos actualizados.');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 const term=search.toLowerCase();
 const bookings=data?.bookings.filter(b=>(statusFilter==='all'||b.status===statusFilter)&&`${b.date} ${b.name??''} ${b.department??''} ${b.dni??''}`.toLowerCase().includes(term))??[];
 const residents=data?.users.filter(u=>`${u.name} ${u.dni} ${u.department}`.toLowerCase().includes(term))??[];
 function exportCsv(){const rows=[['Fecha','Turno','Estado','Residente','Departamento','DNI','Observación'],...bookings.map(b=>[b.date,`${b.slot}:00`,b.status,b.name??'',b.department??'',b.dni??'',b.note])];const safe=(v:string)=>'"'+(/^[=+@\-\t\r]/.test(v)?"'":'')+v.replace(/"/g,'""')+'"';const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(safe).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='reservas-balcones-riviera.csv';a.click();URL.revokeObjectURL(url);}
 return <>{error&&<div className="error-banner" role="alert">{error}<button className="text-button" onClick={()=>void load()}>Reintentar</button></div>}<div className="admin-stats"><div><span className="stat-icon"><CalendarDays/></span><section><p>Reservas confirmadas</p><strong>{data?.bookings.filter(b=>b.status==='confirmed').length??'—'}</strong></section></div><div><span className="stat-icon"><Users/></span><section><p>Residentes activos</p><strong>{data?.users.filter(u=>u.role==='resident'&&u.status==='active').length??'—'}</strong></section></div><div><span className="stat-icon"><LockKeyhole/></span><section><p>Turnos bloqueados</p><strong>{data?.bookings.filter(b=>b.status==='blocked').length??'—'}</strong></section></div></div>
 <Tabs defaultValue="bookings" className="admin-tabs"><TabsList className="admin-tabs-list"><TabsTrigger value="bookings"><CalendarDays size={16}/>Reservas</TabsTrigger><TabsTrigger value="users"><Users size={16}/>Residentes</TabsTrigger><TabsTrigger value="settings"><Settings2 size={16}/>Reglamento y plazos</TabsTrigger><TabsTrigger value="audit"><History size={16}/>Actividad</TabsTrigger></TabsList>
 <TabsContent value="bookings"><section className="content-card admin-card"><div className="section-toolbar"><div><h2>Reservas del edificio</h2><p>{loading?'Actualizando…':`${bookings.length} registros`}</p></div><div className="toolbar-buttons"><button className="btn secondary" onClick={()=>open('block')}><LockKeyhole size={16}/>Bloquear turno</button><button className="btn primary" onClick={()=>open('reserve')}><Plus size={16}/>Nueva reserva</button></div></div><div className="table-filters"><label className="search-box"><Search size={17}/><input aria-label="Buscar reservas" placeholder="Buscar por residente, depto. o fecha" value={search} onChange={e=>setSearch(e.target.value)}/></label><Choice label="Estado" value={statusFilter} onChange={setStatusFilter} options={[{value:'all',label:'Todos los estados'},{value:'confirmed',label:'Confirmadas'},{value:'blocked',label:'Bloqueadas'},{value:'cancelled',label:'Canceladas'}]}/><button className="btn secondary" onClick={exportCsv} disabled={!data}><Download size={16}/>Exportar</button></div><Table><TableHeader><TableRow><TableHead>Fecha y turno</TableHead><TableHead>Residente</TableHead><TableHead>Departamento</TableHead><TableHead>Estado</TableHead><TableHead>Acciones</TableHead></TableRow></TableHeader><TableBody>{bookings.map(b=><TableRow key={b.id}><TableCell><strong>{dateLabel(b.date,{day:'2-digit',month:'short',year:'numeric'})}</strong><small className="cell-sub">{b.slot===12?'Mediodía':'Noche'} · {b.slot}:00 h</small></TableCell><TableCell>{b.name||'Administración'}<small className="cell-sub">{b.note|| (b.dni?`DNI ${b.dni}`:'Bloqueo de disponibilidad')}</small></TableCell><TableCell>{b.department||'—'}</TableCell><TableCell><span className={`badge ${b.status}`}>{b.status==='confirmed'?'Confirmada':b.status==='blocked'?'Bloqueada':'Cancelada'}</span></TableCell><TableCell>{b.status!=='cancelled'&&<button className="text-button danger-text" onClick={()=>setCancel(b)}>{b.status==='blocked'?'Desbloquear':'Cancelar'}</button>}</TableCell></TableRow>)}</TableBody></Table>{!bookings.length&&<div className="table-empty">{loading?'Cargando reservas…':'No hay reservas con estos filtros.'}</div>}</section></TabsContent>
 <TabsContent value="users"><section className="content-card admin-card"><div className="section-toolbar"><div><h2>Residentes y accesos</h2><p>Gestioná los datos y permisos de las cuentas registradas.</p></div><button className="icon-button" onClick={()=>void load()} aria-label="Actualizar residentes"><RefreshCw size={18}/></button></div><div className="table-filters"><label className="search-box"><Search size={17}/><input aria-label="Buscar residentes" placeholder="Nombre, DNI o departamento" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><Table><TableHeader><TableRow><TableHead>Nombre y DNI</TableHead><TableHead>Departamento</TableHead><TableHead>Rol</TableHead><TableHead>Estado</TableHead><TableHead>Acciones</TableHead></TableRow></TableHeader><TableBody>{residents.map(u=><TableRow key={u.id}><TableCell><strong>{u.name}</strong><small className="cell-sub">{u.dni}</small></TableCell><TableCell>{u.department}</TableCell><TableCell>{u.role==='admin'?'Administración':'Residente'}</TableCell><TableCell><span className={`badge ${u.status==='active'?'confirmed':'cancelled'}`}>{u.status==='active'?'Activo':'Suspendido'}</span></TableCell><TableCell><div className="row-actions"><button className="icon-button" aria-label={`Editar ${u.name}`} onClick={()=>open('user',u)}><Edit3 size={17}/></button><button className="icon-button" aria-label={`Restablecer contraseña de ${u.name}`} onClick={()=>open('password',u)}><KeyRound size={17}/></button></div></TableCell></TableRow>)}</TableBody></Table>{!residents.length&&<div className="table-empty">No se encontraron residentes.</div>}<p className="small-note panel-footnote">Al suspender una cuenta se cierra su acceso. Sus reservas se conservan para que puedas revisarlas y cancelarlas desde Reservas.</p></section></TabsContent>
 <TabsContent value="settings"><section className="content-card"><h2>Reglamento y condiciones de reserva</h2><p className="muted intro-copy">Los cambios se reflejan en el calendario y se aplican a nuevas operaciones.</p><form onSubmit={saveSettings} className="form-stack"><label className="field"><span>Reglamento visible para los residentes</span><textarea value={rules} onChange={e=>setRules(e.target.value)} rows={17} minLength={20} maxLength={15000} required/></label><div className="form-columns"><Input label="Anticipación máxima (días)" type="number" min="1" max="365" value={advance} onChange={e=>setAdvance(e.target.value)}/><Input label="Cancelación mínima (horas antes)" type="number" min="0" max="168" value={hours} onChange={e=>setHours(e.target.value)}/></div><p className="small-note">Con 0 horas, los vecinos pueden cancelar hasta antes del inicio del turno. Administración puede cancelar cualquier reserva.</p><button className="btn primary self-start" disabled={busy}>{busy?'Guardando…':'Guardar reglamento y plazos'}</button></form></section></TabsContent>
 <TabsContent value="audit"><section className="content-card admin-card"><div className="section-toolbar"><div><h2>Registro de actividad</h2><p>Últimas 100 operaciones del portal.</p></div><ShieldCheck size={24}/></div><Table><TableHeader><TableRow><TableHead>Fecha y hora</TableHead><TableHead>Acción</TableHead><TableHead>Responsable</TableHead></TableRow></TableHeader><TableBody>{data?.audit.map(a=><TableRow key={a.id}><TableCell>{new Date(a.created_at).toLocaleString('es-AR',{timeZone:'America/Argentina/Buenos_Aires'})}</TableCell><TableCell>{a.action}</TableCell><TableCell>{a.name||'Sistema'}</TableCell></TableRow>)}</TableBody></Table>{!data?.audit.length&&<div className="table-empty">Todavía no se registraron operaciones.</div>}</section></TabsContent></Tabs>
 <Dialog open={!!modal} onOpenChange={open=>{if(!open&&!busy)setModal(null);}}><DialogContent className="portal-dialog"><DialogHeader><DialogTitle>{modal==='reserve'?'Nueva reserva':modal==='block'?'Bloquear un turno':modal==='user'?'Editar residente':'Restablecer contraseña'}</DialogTitle><DialogDescription>{modal==='reserve'?'Reservá en nombre de un residente registrado.':modal==='block'?'El turno no estará disponible para reservas.':modal==='user'?'Actualizá los datos y permisos de esta cuenta.':`Asigná una contraseña temporal a ${editing?.name}. Deberá cambiarla al ingresar.`}</DialogDescription></DialogHeader><form className="form-stack" onSubmit={submit} key={`${modal}-${editing?.id}`}>
 {(modal==='reserve'||modal==='block')&&<><Input label="Fecha" type="date" name="date"/><Choice label="Turno" value={slot} onChange={setSlot} options={[{value:'12',label:'Mediodía · 12:00 h'},{value:'20',label:'Noche · 20:00 h'}]}/>{modal==='reserve'&&<Choice label="Residente responsable" value={target} onChange={setTarget} options={data?.users.filter(u=>u.status==='active').map(u=>({value:u.id,label:`${u.name} · ${u.department}`}))??[]}/>}<label className="field"><span>{modal==='block'?'Motivo del bloqueo':'Observación (opcional)'}</span><textarea name="note" maxLength={500} rows={3} required={modal==='block'}/></label><p className="small-note">Esta operación queda registrada a nombre de la administración.</p></>}
 {modal==='user'&&<><Input label="Nombre y apellido" name="name" defaultValue={editing?.name} minLength={3} maxLength={100}/><Input label="DNI o usuario" name="dni" defaultValue={editing?.dni} readOnly={editing?.dni==='administracion'}/><Input label="Departamento" name="department" defaultValue={editing?.department} maxLength={30}/><Choice label="Estado de la cuenta" value={status} onChange={setStatus} options={[{value:'active',label:'Activa'},{value:'suspended',label:'Suspendida'}]}/><Choice label="Permisos" value={role} onChange={setRole} options={[{value:'resident',label:'Residente'},{value:'admin',label:'Administración — acceso completo'}]}/>{role==='admin'&&<p className="small-note">Esta cuenta podrá gestionar todos los vecinos, reservas y reglamento.</p>}</>}
 {modal==='password'&&<><Input label="Contraseña temporal" name="password" type="password" minLength={12} maxLength={128} autoComplete="new-password"/><p className="small-note">Mínimo 12 caracteres. Se cerrarán las sesiones de esta cuenta. Compartí la contraseña directamente con el residente.</p></>}
 {formError&&<div className="form-error" role="alert">{formError}</div>}<button className="btn primary full" disabled={busy}>{busy?'Guardando…':modal==='block'?'Bloquear turno':modal==='reserve'?'Confirmar reserva':'Guardar cambios'}</button></form></DialogContent></Dialog>
 <AlertDialog open={!!cancel} onOpenChange={open=>{if(!open&&!busy)setCancel(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{cancel?.status==='blocked'?'¿Desbloquear este turno?':'¿Cancelar esta reserva?'}</AlertDialogTitle><AlertDialogDescription>{cancel&&`${dateLabel(cancel.date)} · ${cancel.slot}:00 h. El turno quedará nuevamente disponible. Esta acción se registrará en el historial.`}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Volver</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void cancelTurn();}}>{busy?'Procesando…':'Liberar turno'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </>;
}
