"use client";
import {useState,useEffect,useCallback,useRef,FormEvent} from 'react';
import {Building2,CalendarDays,ClipboardList,BookOpen,ShieldCheck,ArrowUpRight,ChevronLeft,ChevronRight,Sun,Moon,LockKeyhole,LogIn,Info,LogOut,Plus,Check,RefreshCw,UserRound,Loader2} from 'lucide-react';
import {Sidebar,SidebarContent,SidebarFooter,SidebarHeader,SidebarProvider,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Toaster,toast} from 'sonner';
import {AdminPanel} from '@/components/admin-panel';
import {api,dateLabel,type PortalData,type Booking,type User} from '@/lib/types';
const weekdays=['LUN','MAR','MIÉ','JUE','VIE','SÁB','DOM'];
const argentinaDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Argentina/Buenos_Aires',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const navItems=[{id:'calendar',label:'Calendario',icon:CalendarDays},{id:'mine',label:'Mis reservas',icon:ClipboardList},{id:'rules',label:'Reglamento',icon:BookOpen},{id:'admin',label:'Administración',icon:ShieldCheck}];
function Navigation({view,onNavigate}:{view:string;onNavigate:(v:string)=>void}){const {setOpenMobile}=useSidebar();return <><nav className="main-nav">{navItems.map(({id,label,icon:Icon})=><button key={id} className={view===id?'active':''} onClick={()=>{onNavigate(id);setOpenMobile(false);}}><Icon/>{label}</button>)}</nav></>;}
export default function Portal(){
 const [today,setToday]=useState(argentinaDate),[month,setMonth]=useState(()=>argentinaDate().slice(0,7)),[selected,setSelected]=useState(argentinaDate);
 const [view,setView]=useState('calendar'),[data,setData]=useState<PortalData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [auth,setAuth]=useState<'login'|'register'|'password'|null>(null),[booking,setBooking]=useState<number|null>(null),[cancel,setCancel]=useState<Booking|null>(null),[busy,setBusy]=useState(false),[accepted,setAccepted]=useState(false);
 const [rulesOpen,setRulesOpen]=useState(false),[authError,setAuthError]=useState(''),[bookingError,setBookingError]=useState('');
 const [adminRevision,setAdminRevision]=useState(0);const requestId=useRef(0);
 const user=data?.user??null;
 const refresh=useCallback(async()=>{const id=++requestId.current;setLoading(true);try{const next=await api<PortalData>(`/api/portal?month=${month}`);if(id!==requestId.current)return;setData(next);setToday(next.today);setError('');}catch(e){if(id===requestId.current)setError((e as Error).message);}finally{if(id===requestId.current)setLoading(false);}},[month]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),60000);return()=>clearInterval(timer);},[refresh]);
 useEffect(()=>{if(user?.must_change_password)setAuth('password');},[user?.must_change_password]);
 useEffect(()=>{const next=location.hash.slice(1);if(navItems.some(x=>x.id===next))setView(next);const change=()=>{const hash=location.hash.slice(1);if(navItems.some(x=>x.id===hash))setView(hash);};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
 function navigate(v:string){setView(v);location.hash=v;}
 function openAuth(mode:'login'|'register'|'password'){setAuthError('');setAccepted(false);setAuth(mode);}
 const allCount=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate();
 const offset=(new Date(month+'-01T12:00:00').getDay()+6)%7;
 const maxDate=(()=>{const d=new Date(today+'T12:00:00');d.setDate(d.getDate()+(data?.settings.advance_days??90));return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;})();
 const slotStatus=(date:string,slot:number)=>{if(error||!data||data.today!==today)return 'unknown';const occupied=data.slots.find(x=>x.date===date&&x.slot===slot);if(occupied)return occupied.status;return date<today||date>maxDate||(date===today&&slot<=data.hour)?'past':'available';};
 const statusLabel=(status:string)=>({available:'Disponible',confirmed:'Reservado',blocked:'Bloqueado',past:'No disponible',unknown:'Sin información'}[status]||status);
 function changeMonth(delta:number){const d=new Date(month+'-01T12:00:00');d.setMonth(d.getMonth()+delta);const next=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;setMonth(next);setSelected(next===today.slice(0,7)?today:next+'-01');setData(null);}
 function startBooking(slot:number){if(!user){openAuth('login');return;}setAccepted(false);setBookingError('');setBooking(slot);}
 async function onAuth(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setAuthError('');try{await api('/api/auth',{action:auth,...Object.fromEntries(form),acceptRules:accepted});setAuth(null);await refresh();toast.success(auth==='register'?'Tu cuenta está lista. Ya podés reservar.':auth==='password'?'Contraseña actualizada. Ingresá nuevamente.':'Sesión iniciada.');if(auth==='password'){setAuth('login');setView('calendar');}}catch(e){setAuthError((e as Error).message);}finally{setBusy(false);}}
 async function reserve(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setBookingError('');try{await api('/api/bookings',{action:'reserve',date:selected,slot:booking,acceptRules:accepted});setBooking(null);await refresh();toast.success('Reserva confirmada. Podés verla en Mis reservas.');setAdminRevision(x=>x+1);}catch(e){setBookingError((e as Error).message);await refresh();}finally{setBusy(false);}}
 async function cancelBooking(){if(!cancel)return;setBusy(true);try{await api('/api/bookings',{action:'cancel',id:cancel.id});setCancel(null);await refresh();toast.success('Reserva cancelada. El turno vuelve a estar disponible.');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 async function logout(){try{await api('/api/auth',{action:'logout'});setData(null);setView('calendar');await refresh();toast.success('Sesión cerrada.');}catch(e){toast.error((e as Error).message);}}
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:'show_calendar_month',description:'Muestra un mes del calendario del quincho. No crea ni cancela reservas.',inputSchema:{type:'object',properties:{month:{type:'string',pattern:'^\\d{4}-(0[1-9]|1[0-2])$'}},required:['month'],additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{const m=(input as {month?:string})?.month;if(!m||!/^\d{4}-(0[1-9]|1[0-2])$/.test(m))throw new Error('Mes inválido');const next=await api<PortalData>(`/api/portal?month=${m}`);setMonth(m);setSelected(m+'-01');setData(next);setToday(next.today);setView('calendar');return {month:m,slots:next.slots};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 return <SidebarProvider><Sidebar className="riviera-sidebar"><SidebarHeader><div className="brand"><span className="brand-mark"><Building2 size={25}/></span><div>BALCONES<span>DE LA RIVIERA</span></div></div><div className="building-label">PORTAL DEL CONSORCIO</div></SidebarHeader><SidebarContent><Navigation view={view} onNavigate={navigate}/></SidebarContent><SidebarFooter><div className="sidebar-note"><Building2 size={20}/><strong>Un espacio compartido.<br/>Una buena convivencia.</strong><p>Gestioná el uso del quincho de tu edificio desde un solo lugar.</p></div><div className="sidebar-bottom">Balcones de la Riviera<span>Portal de residentes</span></div></SidebarFooter></Sidebar>
 <div className="app-body"><header className="topbar"><div className="breadcrumb"><SidebarTrigger/><span>Espacios comunes</span><span>/</span><strong>Quincho</strong></div><div className="account-actions">{user?<><button className="account-name" onClick={()=>openAuth('password')} title="Cambiar contraseña"><span className="avatar">{user.name.slice(0,1)}</span><span>{user.name}<small>{user.role==='admin'?'Administración':`Depto. ${user.department}`}</small></span></button><button className="icon-button" aria-label="Cerrar sesión" onClick={logout}><LogOut size={18}/></button></>:<button className="btn secondary" onClick={()=>openAuth('login')}><LogIn size={16}/>Ingresar</button>}</div></header>
 <main className="workspace"><div className="page-heading"><div><div className="eyebrow">{view==='admin'?'ADMINISTRACIÓN DEL CONSORCIO':'RESERVAS DEL QUINCHO'}</div><h1>{view==='calendar'?'Organizá tu próximo encuentro.':view==='mine'?'Mis reservas':view==='rules'?'Reglamento del quincho':'Panel de administración'}</h1><p>{view==='calendar'?'Consultá la disponibilidad y reservá tu lugar.':view==='mine'?'Tus próximos encuentros y el historial de uso.':view==='rules'?'Pautas para compartir y cuidar nuestro espacio.':'Reservas, residentes y condiciones de uso, en un solo lugar.'}</p></div><span className="outlined-tag"><Building2 size={15}/>Balcones de la Riviera</span></div>
 {error&&<div className="error-banner" role="alert"><Info size={19}/><span>{error}</span><button className="text-button" onClick={()=>void refresh()}><RefreshCw size={15}/>Reintentar</button></div>}
 {view==='calendar'&&<>{!user&&<div className="info-banner"><span className="info-icon"><Info size={20}/></span><div><strong>El calendario está abierto para todos.</strong><p>Para hacer una reserva, ingresá o registrate con tus datos de residente.</p></div><button className="text-button" onClick={()=>openAuth('register')}>Crear una cuenta <ArrowUpRight size={17}/></button></div>}
 <div className="calendar-layout"><section className="calendar-card" aria-label="Calendario de disponibilidad" aria-busy={loading}><div className="calendar-toolbar"><div><h2 className="capitalize">{dateLabel(month+'-01',{month:'long',year:'numeric'})}</h2><span>{loading?'Actualizando disponibilidad…':'Disponibilidad del quincho'}</span></div><div className="month-controls"><button className="btn secondary" onClick={()=>{setMonth(today.slice(0,7));setSelected(today);}}>Hoy</button><button aria-label="Mes anterior" onClick={()=>changeMonth(-1)}><ChevronLeft size={19}/></button><button aria-label="Mes siguiente" onClick={()=>changeMonth(1)}><ChevronRight size={19}/></button></div></div><div className="calendar-weekdays">{weekdays.map(d=><span key={d}>{d}</span>)}</div><div className="calendar-grid">{Array.from({length:Math.ceil((allCount+offset)/7)*7},(_,i)=>{const day=i-offset+1;const date=`${month}-${String(day).padStart(2,'0')}`;const outside=day<1||day>allCount;return <button key={i} aria-label={outside?'Fuera del mes':`${dateLabel(date)}. Mediodía: ${statusLabel(slotStatus(date,12))}. Noche: ${statusLabel(slotStatus(date,20))}`} aria-pressed={!outside&&date===selected} className={`calendar-day ${outside?'outside':''} ${date===selected?'selected':''} ${date<today?'past-day':''}`} disabled={outside} onClick={()=>setSelected(date)}><span className={`day-number ${date===today?'today':''}`}>{!outside?day:''}</span>{!outside&&[12,20].map(slot=><span key={slot} className={`slot-line ${slotStatus(date,slot)}`}>{slot===12?<Sun size={12}/>:<Moon size={12}/>}<span>{slot}:00</span><i className={`dot ${slotStatus(date,slot)==='confirmed'?'reserved':slotStatus(date,slot)}`}/></span>)}</button>})}</div><div className="calendar-legend"><span><i className="dot available"/>Disponible</span><span><i className="dot reserved"/>Reservado</span><span><i className="dot blocked"/>No disponible</span><small>Hora de Argentina (GMT−3)</small></div></section>
 <aside className="right-panel"><section className="day-card"><div className="eyebrow">DÍA SELECCIONADO</div><h2>{dateLabel(selected,{day:'numeric',month:'long'})}</h2><p className="capitalize">{dateLabel(selected,{weekday:'long'})} · Dos turnos diarios</p>{[12,20].map(slot=>{const status=slotStatus(selected,slot);return <div key={slot} className="turn-wrapper"><div className="turn-card"><span className={`turn-icon ${slot===20?'night':''}`}>{slot===12?<Sun/>:<Moon/>}</span><div><strong>{slot===12?'Mediodía':'Noche'}</strong><p>Desde las {slot}:00 h</p></div><span className={`status-label ${status}`}>{statusLabel(status)}</span></div>{user&&status==='available'&&<button className="btn primary full reserve-turn" disabled={loading} onClick={()=>startBooking(slot)}><Plus size={16}/>Reservar {slot===12?'mediodía':'noche'}</button>}</div>})}{!user&&<><div className="signin-hint"><LockKeyhole size={17}/><span>Necesitás una cuenta de residente para reservar.</span></div><button className="btn primary full" onClick={()=>openAuth('login')}>Ingresar para reservar <ArrowUpRight size={17}/></button></>}{user&&<p className="small-note">Reservas con hasta {data?.settings.advance_days??90} días de anticipación.</p>}</section><section className="rules-callout"><BookOpen size={22}/><h3>Disfrutemos el quincho.<br/>Cuidemos el espacio.</h3><p>Antes de reservar, conocé las normas de uso y convivencia.</p><button className="text-button" onClick={()=>navigate('rules')}>Consultar reglamento <ArrowUpRight size={16}/></button></section></aside></div></>}
 {view==='rules'&&<section className="content-card rules-content"><div className="section-icon"><BookOpen/></div><h2>Normas de uso y convivencia</h2><div className="rules-meta"><span>Mediodía · desde las 12:00 h</span><span>Noche · desde las 20:00 h</span></div>{data?<><p className="rules-text">{data.settings.rules.replace(/\\n/g,'\n')}</p><div className="info-banner"><Info size={19}/><p>Podés reservar con hasta {data.settings.advance_days} días de anticipación. {data.settings.cancellation_hours?`Las cancelaciones se permiten hasta ${data.settings.cancellation_hours} horas antes del turno.`:'Podés cancelar hasta antes del inicio del turno.'}</p></div><p className="small-note">Última actualización: {new Date(data.settings.updated_at).toLocaleDateString('es-AR')}</p></>:<p>{error?'No se pudo cargar el reglamento.':'Cargando reglamento…'}</p>}</section>}
 {view==='mine'&&(!user?<AccessCard title="Tus reservas, siempre a mano" description="Ingresá con tu DNI y contraseña para consultar o cancelar tus reservas." onLogin={()=>openAuth('login')}/>:<div className="reservation-list">{!data?.mine.length?<section className="content-card empty-state"><CalendarDays size={36}/><h2>Todavía no tenés reservas</h2><p>Elegí un día disponible en el calendario para organizar tu próximo encuentro.</p><button className="btn primary" onClick={()=>navigate('calendar')}>Ver calendario</button></section>:data.mine.map(b=><section className="reservation-row" key={b.id}><div className="reservation-date"><strong>{new Date(b.date+'T12:00:00').getDate()}</strong><span>{dateLabel(b.date,{month:'short'})}</span></div><div className="reservation-info"><h3>{b.slot===12?'Mediodía':'Noche'} · {b.slot}:00 h</h3><p>{dateLabel(b.date)} · Depto. {user.department}</p>{b.note&&<p>{b.note}</p>}</div><span className={`badge ${b.status}`}>{b.status==='confirmed'?'Confirmada':b.status==='cancelled'?'Cancelada':'Bloqueada'}</span>{b.status==='confirmed'&&new Date(`${b.date}T${b.slot}:00:00-03:00`).getTime()>Date.now()+(data?.settings.cancellation_hours??0)*3600000&&<button className="btn secondary" onClick={()=>setCancel(b)}>Cancelar reserva</button>}</section>)}</div>)}
 {view==='admin'&&(user?.role==='admin'?<AdminPanel user={user} settings={data!.settings} revision={adminRevision} onChanged={refresh}/>:<AccessCard title="Acceso de administración" description={user?'Tu cuenta de residente no tiene permisos de administración.':'Ingresá con la cuenta de administración para gestionar el edificio.'} onLogin={()=>openAuth('login')}/>)}
 <footer className="page-footer"><span>Administración · Balcones de la Riviera</span><span>Espacios comunes, buena convivencia.</span></footer></main></div>
 <Dialog open={auth!==null} onOpenChange={open=>{if(!open&&!busy){setAuth(null);setAuthError('');}}}><DialogContent className="portal-dialog"><DialogHeader><div className="section-icon"><UserRound/></div><DialogTitle>{auth==='register'?'Crear cuenta de residente':auth==='password'?'Cambiar contraseña':'Bienvenido a tu edificio'}</DialogTitle><DialogDescription>{auth==='register'?'Registrate con tus datos para reservar el quincho.':auth==='password'?'Elegí una contraseña de al menos 12 caracteres. Al guardar, cerramos las sesiones abiertas.':'Ingresá con tu DNI y contraseña. Administración: utilizá tu usuario asignado.'}</DialogDescription></DialogHeader><form className="form-stack" onSubmit={onAuth} key={auth}>{auth==='register'&&<><Field label="Nombre y apellido" name="name" autoComplete="name" minLength={3} maxLength={100}/><Field label="Número de departamento" name="department" placeholder="Ej.: 4B" maxLength={30}/></>}{auth!=='password'&&<Field label={auth==='register'?'DNI':'DNI o usuario de administración'} name="dni" inputMode={auth==='register'?'numeric':'text'} autoComplete="username" placeholder={auth==='register'?'Sin puntos ni espacios':'Tu DNI'} maxLength={30}/>} {auth==='password'&&<Field label="Contraseña actual" name="currentPassword" type="password" autoComplete="current-password" maxLength={128}/>}<Field label={auth==='password'?'Nueva contraseña':'Contraseña'} name="password" type="password" autoComplete={auth==='login'?'current-password':'new-password'} minLength={auth==='login'?1:12} maxLength={128}/>{auth!=='login'&&<p className="small-note">Usá al menos 12 caracteres. Podés combinar varias palabras.</p>}{auth==='register'&&<><label className="check-label"><Checkbox checked={accepted} onCheckedChange={v=>setAccepted(v===true)}/><span>Confirmo mis datos de residente y acepto el <button className="inline-link" type="button" onClick={()=>setRulesOpen(true)}>reglamento del quincho</button>.</span></label><p className="small-note">El DNI se utiliza para identificar tu cuenta. Solo la administración accede a los datos de todos los residentes.</p></>}{authError&&<div role="alert" className="form-error">{authError}</div>}<button className="btn primary full" disabled={busy||(auth==='register'&&!accepted)}>{busy?<Loader2 size={17} className="animate-spin"/>:null}{busy?'Procesando…':auth==='register'?'Crear mi cuenta':auth==='password'?'Guardar contraseña':'Ingresar'}</button>{auth==='login'&&<><p className="form-bottom">¿Todavía no tenés cuenta? <button type="button" onClick={()=>openAuth('register')} className="inline-link">Registrate</button></p><p className="small-note">Si olvidaste tu contraseña, solicitá a la administración que la restablezca.</p></>}{auth==='register'&&<p className="form-bottom">¿Ya estás registrado? <button type="button" className="inline-link" onClick={()=>openAuth('login')}>Ingresar</button></p>}</form></DialogContent></Dialog>
 <Dialog open={booking!==null} onOpenChange={open=>{if(!open&&!busy)setBooking(null);}}><DialogContent className="portal-dialog"><DialogHeader><DialogTitle>Confirmar reserva</DialogTitle><DialogDescription>El turno quedará reservado a tu nombre y departamento.</DialogDescription></DialogHeader><form onSubmit={reserve} className="form-stack"><div className="booking-summary"><CalendarDays/><div><strong>{dateLabel(selected)}</strong><p>{booking===12?'Mediodía':'Noche'} · Desde las {booking}:00 h</p><p>{user?.name} · Depto. {user?.department}</p></div></div><label className="check-label"><Checkbox checked={accepted} onCheckedChange={v=>setAccepted(v===true)}/><span>Leí y acepto el <button type="button" className="inline-link" onClick={()=>setRulesOpen(true)}>reglamento de uso</button>.</span></label>{bookingError&&<div role="alert" className="form-error">{bookingError}</div>}<button disabled={busy||!accepted} className="btn primary full">{busy?'Confirmando…':'Confirmar reserva'}<Check size={17}/></button></form></DialogContent></Dialog>
 <Dialog open={rulesOpen} onOpenChange={setRulesOpen}><DialogContent className="portal-dialog"><DialogHeader><DialogTitle>Reglamento del quincho</DialogTitle><DialogDescription>Condiciones vigentes de uso del espacio.</DialogDescription></DialogHeader><p className="rules-text">{data?.settings.rules.replace(/\\n/g,'\n')||'No se pudo cargar el reglamento.'}</p></DialogContent></Dialog>
 <AlertDialog open={!!cancel} onOpenChange={open=>{if(!open&&!busy)setCancel(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>¿Cancelar esta reserva?</AlertDialogTitle><AlertDialogDescription>{cancel&&`${dateLabel(cancel.date)} · ${cancel.slot}:00 h. El turno volverá a estar disponible para otros vecinos.`}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Conservar reserva</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void cancelBooking();}}>{busy?'Cancelando…':'Cancelar reserva'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog><Toaster position="bottom-right" richColors closeButton/>
 </SidebarProvider>;
}
export function Field({label,...props}:{label:string}&React.InputHTMLAttributes<HTMLInputElement>){return <label className="field"><span>{label}</span><input required {...props}/></label>;}
function AccessCard({title,description,onLogin}:{title:string;description:string;onLogin:()=>void}){return <section className="content-card empty-state"><LockKeyhole size={35}/><h2>{title}</h2><p>{description}</p><button className="btn primary" onClick={onLogin}><LogIn size={17}/>Ingresar</button></section>;}
